PATH_REFERENCE_GRAPH = "./data/graph/reference.txt"
PATH_REFERENCE_GRAPH_FIGURE = "./data/graph/reference.png"
PATH_EMPIRICAL_SEARCH = "./data/parameters/empirical_search_exp.txt"
PATH_NODE_FILE = "./data/grenoble/nodes.csv"
PATH_EDGE_FILE = "./data/grenoble/distances.csv"
